version: '3.8'
services:
  ie307-be: 
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 4000:4000
    command: bun dev
    volumes:
      - data:/home/node/app

volumes:
  data:
