name: Pre Pull Request
on:
  pull_request:
    branches:
      - "master"
jobs:
  test_preview:
    strategy:
      matrix:
        version: [1.x.x]
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v4

      - name: Setup Bunx
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{matrix.version}}
      - name: Install package use Bun
        run: |
          echo "We using bun to install package!"
          bun install

      - name: Check format
        run: |
          echo "Using pettier check"
          bun format
      - name: Build bunx
        run: |
          echo "Bun is Building"
          bun build:server
